name = "flash"
description = "Very fast model for testing"

base_url = "https://openrouter.ai/api/v1"
api_key = ""
api_key_env = "OPENROUTER_API_KEY"

default_model = "qwen/qwen3.5-flash-02-23"
default_effort = "none"
max_output_tokens = 64000
compaction_at_tokens = 500000

skills_dir = "./skills"
enabled_skills = []

enabled_tools = [
  "read_file",
  "edit_file",
  "write_file",
  "glob",
  "grep",
  "apply_patch",
  "bash",
  "web_search",
  "web_fetch",
]

system_prompt_file = "../prompts/coder.md"

timeout = "1h"
